accounts/urls.py
# accounts/urls.py
from django.urls import path

from . import views

app_name = 'accounts'
urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup'),
]

betting/urls.py
from django.urls import path, include

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('market/<int:id>/', views.market),
    path('placeBet/<int:market_id>/', views.place_bet),
    ]

ouccc/urls.py
from django.contrib import admin
from django.urls import include, path
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('betting/', include('betting.urls')),
    path('xchange/', include('xchange.urls')),
    path('', views.home, name='Home'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')) # new
]

handler404 = 'ouccc.views.handler404'
handler500 = 'ouccc.views.handler500'
# handler403 = views.handler403

xchange/urls.py
# from django.conf.urls import include, url
# from django.contrib import admin
from xchange import views
# from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path

# For namespacing
app_name = 'xchange'

urlpatterns = [
    path('', views.index, name='index'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('profile/', views.profile, name='profile'),
    path('trades/', views.trades, name='trades'),
    path('incoming_trades/', views.incoming_trades, name='incoming_trades'),
    path('past_trades/', views.past_trades, name='past_trades'),
    path('make_trade/', views.make_trade, name='make_trade'),
    path('create_trade/', views.create_trade, name='create_trade'),
    path('respond_to_trade/', views.respond_to_trade, name='respond_to_trade'),
    path('respond_to_open_trade/', views.respond_to_open_trade, name='respond_to_open_trade'),
    path('marketplace/', views.marketplace, name='marketplace'),
    path('marketplace_selling/', views.marketplace_selling, name='marketplace_selling'),
    path('marketplace_buying/', views.marketplace_buying, name='marketplace_buying'),
    path('get_investors_for_runner/', views.get_investors_for_runner, name='get_investors_for_runner'),
]


#path('register/', views.register, name='register'),
    #path('login/', auth_views.login, {'template_name': 'login.html'}, name='login'),
    #path('login/', views.login, name='login'),
    #path('logout/', views.logout, name='logout'),
    #path('logout/', 'django.contrib.authviews.logout', {'next_page': '/'}),


# admin.autodiscover()

#urlpatterns = patterns('',
 #   .......
#) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# urlpatterns += staticfiles_urlpatterns()

xchange/forms.py
from django import forms

class UserRegistrationForm(forms.Form):
    username = forms.CharField(
        required = True,
        label = 'Username',
        max_length = 32
    )
    email = forms.CharField(
        required = True,
        label = 'Email',
        max_length = 32,
    )
    password = forms.CharField(
        required = True,
        label = 'Password',
        max_length = 32,
        widget = forms.PasswordInput()
    )

xchange/views.py
from django.shortcuts import render_to_response, render, redirect
from django.template import RequestContext

from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import UserCreationForm

#from django.contrib.auth.views import logout

from django.contrib.auth.models import User
from django.http import HttpResponseRedirect, HttpResponse
from django import forms
from .forms import UserRegistrationForm
from django.db.models import Q
from .models import Share, Trade, Investor, Runner, OpenTrade

from django.contrib.auth.decorators import login_required
from django.http.response import JsonResponse
import json

def index(request):
	# context = {}
	# return render(request, 'xchange.html', context)

	# return dashboard(request)

	return marketplace(request)

def dashboard(request):

	if request.user.is_authenticated:
		investor = request.user.investor

		shares = Share.objects.filter(owner=request.user.investor)
		collated_shares = investor.get_shares()
		return render(request, 'dashboard.html', {'shares': shares, 'collated_shares': collated_shares})
	else:
		return render(request, 'xchange.html', {})

def profile(request):
	if request.user.is_authenticated:
		#shares = Share.objects.filter(owner=request.user.investor)
		return render(request, 'profile.html', {})
	else:
		return render(request, 'xchange.html', {})

def marketplace(request):
	if request.user.is_authenticated:
		#shares = Share.objects.filter(owner=request.user.investor)

		# Remove testing:
		#investor = request.user.investor
		#open_trade = OpenTrade.objects.filter(buyer=investor).first()
		#investor.can_fulfil_trade(open_trade)

		return render(request, 'marketplace.html', {})
	else:
		return render(request, 'xchange.html', {})

@login_required
def marketplace_buying(request):

	# Get open trades where the buyer is known
	buy_trades = OpenTrade.objects.filter(Q(status=Trade.PENDING)).order_by('-updated')

	return render(request, 'marketplace_buy.html', {'buy_trades': buy_trades})

@login_required
def marketplace_selling(request):

	# Get trades where someone wants to sell a share but there is no buyer
	sell_trades = Trade.objects.filter(Q(buyer=None) & Q(status=Trade.PENDING)).order_by('-updated')

	return render(request, 'marketplace_sell.html', {'sell_trades': sell_trades})



@login_required
def get_direct_trades(investor):
	direct_trades = Trade.objects.filter(((Q(buyer=investor) & ~Q(seller=None)) | Q(seller=investor) & ~Q(buyer=None))  & Q(status=Trade.PENDING)).order_by('-updated')

	return direct_trades

@login_required
def get_marketplace_sell_trades(investor):
	sell_trades = Trade.objects.filter(Q(seller=investor) & Q(buyer=None) & Q(status=Trade.PENDING)).order_by('-updated')

	return sell_trades

@login_required
def get_marketplace_buy_trades(investor):

	buy_trades = OpenTrade.objects.filter(Q(buyer=investor) & Q(status=Trade.PENDING)).order_by('-updated')

	return buy_trades

@login_required
def incoming_trades(request):

	investor = request.user.investor

	# Direct trades - i.e. both buyer and seller are defined, and this user is one of them
	direct_trades = get_direct_trades(investor)

	# Open trades where this is the seller
	buy_trades = get_marketplace_buy_trades(investor)

	sell_trades = get_marketplace_sell_trades(investor)

	return render(request, 'incoming_trades.html', {'direct_trades': direct_trades, 'buy_trades': buy_trades, 'sell_trades': sell_trades})

 
@login_required
def past_trades(request):

	investor = request.user.investor
	past_trades = Trade.objects.filter((Q(buyer=investor) | Q(seller=investor)) & ~Q(status=Trade.PENDING) ).order_by('-updated')

	return render(request, 'past_trades.html', {'past_trades': past_trades})

@login_required
def make_trade(request):

	investor = request.user.investor

	#shares = Share.objects.filter(owner=investor)
	sellable_shares = investor.get_sellable_shares()

	print(sellable_shares)

	# Get all shares excluding those from the current investor
	all_collated_shares = Investor.get_all_shares(investor)
	
	other_investors = Investor.objects.filter(~Q(user = request.user))

	return render(request, 'make_trade.html', {'sellable_shares': sellable_shares, 'other_investors': other_investors,
		'all_collated_shares': all_collated_shares})	
 

def get_investors_for_runner_obj(runner):
	shares = Share.objects.filter(Q(runner=runner))

	print('Shares for runner' + str(shares))

	# Now get a list of investors who own these shares, and how many they own each
	investors = []

	for s in shares:
		
		investor = s.owner

		#Check if we already have this investor
		investor_exists = False
		for i in investors:
			if i['investor_id'] == investor.id:
				investor_exists = True
				i['num_shares'] = i['num_shares'] + 1

		if not investor_exists:
			investors.append({'investor_id': investor.id, 'investor_name': str(investor), 'num_shares': 1})

	print(investors)

	return investors

def get_investors_for_runner(request):
	print('get_investors_for_runner')

	status = 0

	runner_id = int(request.GET['runner_id'])
	print('Runner id: ' + str(runner_id))
	
	runner = Runner.objects.get(pk=runner_id)

	print('Get investors for runner: ' + str(runner))
	
	investors =  get_investors_for_runner_obj(runner)

	#investors = []
	payload = {'investors': investors}

	return HttpResponse(json.dumps(payload), content_type='application/json')


@login_required
def create_trade(request):

	status = 0
	err_msg = 'Unknown error, sorry!'

	#'user_id': user_id, 'runner_id': runner_id, 'num_shares': num_shares, 'share_price': share_price, 'trade_width': trade_width}


	seller_id = int(request.GET['seller_id'])
	runner_id = int(request.GET['runner_id'])
	num_shares = float(request.GET['num_shares'])
	share_price = float(request.GET['share_price'])
	buyer_id = int(request.GET['buyer_id'])

	print('Create trade - got details')

	# Basic form checks
	if not int(num_shares) == num_shares:
		status = 4
		err_msg = 'Number of shares must be an integer'

	num_shares = int(num_shares)

	if share_price <= 0:
		status = 5
		err_msg = 'Share price must be greater than 0'

	if not status == 0:
		payload = {'status': status, 'err_msg': err_msg}
		return HttpResponse(json.dumps(payload), content_type='application/json')

	# Check trade is legit. i.e. that seller has enough shares


        #	1) You're trying to sell more shares than you have
        #	2) You're trying to buy more shares than someone has
        #	3) You're trying to spend more money than you have

	runner = Runner.objects.get(pk=runner_id)
	creator = request.user.investor

	if seller_id > 0:
		print('Create trade - checking seller')

		seller = Investor.objects.get(pk=seller_id)

		seller_shares = Share.objects.filter(owner=seller, runner=runner)
		if seller_shares.count() < num_shares:
			status = 1
			if seller == creator:
				err_msg = 'You do not have this many shares to sell'
			else:
				err_msg = 'The seller does not have this many share to sell'

	if buyer_id > 0:
		print('Create trade - checking buyer')

		buyer = Investor.objects.get(pk=buyer_id)

		# Only care about insufficient funds if this person is proposing the trade
		if num_shares*share_price > buyer.capital and buyer == creator:
			status = 2
			err_msg = 'You do not have enough capital to make this trade'

	print('Create trade - status' + str(status))

	if status == 0:
		# Execute trade

		# Direct trade
		if buyer_id >= 0 and seller_id >= 0:
			print('Make direct trade')
			buyer = Investor.objects.get(pk=buyer_id)
			seller = Investor.objects.get(pk=seller_id)

			# Find the shares to trade
			shares = Share.objects.filter(owner=seller, runner=runner)[:num_shares]

			print('Got shares')

			for s in shares:
				print(s)
				trade = Trade.objects.create(seller=seller,buyer=buyer, price=share_price, creator=creator, share=s)
				#trade.save()

		# Known seller with specific shares
		elif seller_id >= 0:
			print('Make trade with known seller but no buyer')

			seller = Investor.objects.get(pk=seller_id)

			# Find the shares to trade
			shares = Share.objects.filter(owner=seller, runner=runner)[:num_shares]

			print('Got shares')
			for s in shares:
				print(s)
				trade = Trade.objects.create(seller=seller, share=s, price=share_price, creator=creator)	
				print('Made trade')
				#trade.save()

		# Known buyer but no specific share
		elif buyer_id >= 0:
			print('Make trade with known buyer but no seller')

			buyer = Investor.objects.get(pk=buyer_id)

			for i in range(0,num_shares):
				trade = OpenTrade.objects.create(buyer=buyer, runner=runner, price=share_price, creator=creator)
				#trade.save()

		else:
			# this should never happen - no seller or buyer
			status = -1

	print('Final status: ' + str(status))
	payload = {'status': status, 'err_msg': err_msg}
	return HttpResponse(json.dumps(payload), content_type='application/json')
	

@login_required
def respond_to_trade(request):

	trade_id = int(request.GET['trade_id'])
	response = str(request.GET['response'])

	trade = Trade.objects.get(pk=trade_id)

	# Check that this response is valid (i.e. both parties have sufficient capital, or it's being rejected)
	success = (response == Trade.REJECTED or response == Trade.CANCELLED) or trade.check_if_allowed()

	if success:
		success = trade.set_status(response)
		trade.save()
	
	payload = {'trade_allowed': success}

	return HttpResponse(json.dumps(payload), content_type='application/json')
	#return HttpResponse()

@login_required
def respond_to_open_trade(request):

	trade_id = int(request.GET['trade_id'])
	response = str(request.GET['response'])
	seller_id = int(request.GET['seller_id'])

	trade = OpenTrade.objects.get(pk=trade_id)

	success = True

	# Check that this response is valid (i.e. both parties have sufficient capital, or it's being rejected)
	if response == Trade.REJECTED or response == Trade.CANCELLED:
		trade.status = response;
		trade.save()

	else:
		# Need to convert this to a direct trade, then confirm that trade

xchange/templates/dashboard.html
{% extends 'xchange_base.html' %}
{% load static %}

{% block title %}Dashboard{% endblock %}

{% block page_title %}Your Portfolio{% endblock %}

{% block content %}

<!--Hello, {{ user.username }}. <br><br> -->

<!-- General summary of investor's portfolio and trade options <br><br>-->


Capital: {{user.investor.print_capital}}

<br><br>

Shares: 

{% if shares %}

{% for s in collated_shares %}
{{s.runner}} - {{s.num_shares}} share(s) <br> 
{% endfor %}

{% else %}
You don't have any shares
{% endif %}


{%endblock%}

{% block footer %}

{% endblock %}

xchange/templates/incoming_trades.html
{% if direct_trades or sell_trades or buy_trades %}
<table class="table">
  <tbody>


{% for t in direct_trades %}
    <tr>

      {% if t.creator == t.seller %}

        {% if t.seller == user.investor %}
        <td>You</td>
        <td>want to sell</td>
         <td>{{t.share.runner}}</td>
         <td>to {{t.buyer}} </td>

        {% else %}

        <td>{{t.seller}}</td>
        <td>wants to sell</td>
         <td>{{t.share.runner}}</td>
        <td>to you</td>
        {% endif %}

      {% else %}


          {% if t.buyer == user.investor %}
        <td>You</td>
        <td>want to buy</td>
         <td>{{t.share.runner}}</td>
         <td>from {{t.seller}}</td>

        {% else %}

        <td>{{t.buyer}}</td>
        <td>wants to buy</td>
         <td>{{t.share.runner}}</td>
         <td>from you</td>

        {% endif %}

      {% endif %}


    
      
     



      <td>for {{t.print_price}}</td>
      <td>
       
        
        {% if t.creator == user.investor %}
        <button id="C{{t.id}}" value="C" name="C" onclick="respond_to_trade({{t.id}}, '{{t.CANCELLED}}')">Cancel</button>
        {% else %}
         <button id="A{{t.id}}" value="A" name="A" onclick="respond_to_trade({{t.id}}, '{{t.ACCEPTED}}')" {% if not t.check_if_allowed %}disabled{% endif %}>Accept</button>  
        <button id="D{{t.id}}" value="D" name="D" onclick="respond_to_trade({{t.id}}, '{{t.REJECTED}}')">Reject</button>
        {% endif %}
      </td>
    </tr>
{% endfor %}


{% for t in sell_trades %}
<tr>
<td>You</td>
<td>want to sell</td>
<td>{{t.share.runner}}</td>
<td>to anyone</td>
      <td>for {{t.print_price}}</td>
      <td> <button id="C{{t.id}}" value="C" name="C" onclick="respond_to_trade({{t.id}}, '{{t.CANCELLED}}')">Cancel</button></td>
</tr>
{% endfor %}

{% for t in buy_trades %}
<tr>
<td>You</td>
<td>want to buy</td>
<td>{{t.runner}}</td>
<td>from anyone</td>
      <td>for {{t.print_price}}</td>
      <td> <button id="C{{t.id}}" value="C" name="C" onclick="respond_to_open_trade({{t.id}}, '{{t.CANCELLED}}', {{user.investor.id}})">Cancel</button></td>
</tr>
{% endfor %}

</tbody>
</table>

{% else %}
No active trade requests
{% endif %}

xchange/templates/make_trade.html
<div style="float:left; width:50%; padding-right:2%; border-right:1px #000 solid; height:100%">
<h3>Sell</h3>
{% if sellable_shares|length > 0 %}
    Share: <select name="trade_share" id="trade_share">
    	{% for s in sellable_shares %}

		  <option value="{{s.runner.id}}">{{s.runner}} - {{s.num_shares}} share(s)</option>
	  {% endfor %}
    	
	</select>
	<br>
	Number of shares to trade: <input name="num_shares" id="num_shares" type="number" style="width:40px" value="1"> 
	<br>
	Price per share: £<input name="share_price" id="share_price" type="number" style="width:80px" value="1"> million <br>
	Sell to: <select name="buyer_id" id="buyer_id">
		<option value="-1">--Marketplace--</option>
{% for r in other_investors %}
<option value="{{r.id}}">{{r}}</option>
{% endfor %}
	</select>

	<br>

	<button id="make_trade" value="make_trade" name="make_trade" onClick="makeTradeSell()">Sell</button>

	{% else %}

	You don't have any shares to sell

	{% endif %}


</div>


<div style="float:right; width:50%; padding-left:2%; border-left:1px #000 solid;">
<h3>Buy</h3>
Share: <select name="trade_share_buy" id="trade_share_buy">
	<option value="-1">-- Choose a share --</option>
    	{% for s in all_collated_shares %}
		  <option value="{{s.runner.id}}">{{s.runner}} - {{s.num_shares}} share(s)</option>
	  	{% endfor %}
	  </select>

	  	<br>
Buy from: <select name="seller_id_responsive" id="seller_id_responsive">
		<option value="-1" selected>--Marketplace--</option>
{% for r in other_investors %}
<option value="{{r.id}}">{{r}}</option>
{% endfor %}
	</select>

<br>
Number of shares to buy: <input name="num_shares_buy" id="num_shares_buy" type="number" style="width:40px" value="1"> <br>
Price per share: £<input name="share_price_buy" id="share_price_buy" type="number" style="width:80px" value="1"> million <br>

<button id="make_trade_buy" value="make_trade_buy" name="make_trade_buy" onClick="makeTradeBuy()">Buy</button>

</div>

xchange/templates/marketplace.html
{% extends 'xchange_base.html' %}
{% load static %}

{% block title %}Marketplace{% endblock %}

{% block page_title %}Marketplace{% endblock %}

{% block content %}

<div class="card" style="width: 48%; float:left;">
  <div class="card-body">
    <h2 class="card-title">Buying</h2>
    <!--<h6 class="card-subtitle mb-2 text-muted">Card subtitle</h6>-->
    <p class="card-text">
    	<div id="marketplace_buying">
    	</div>


</p>
    <!--<a href="#" class="card-link">Card link</a>
    <a href="#" class="card-link">Another link</a>-->
  </div>
</div>

<div id="right-container" style="width:48%; float:right;">

<div class="card" style="width: 100%;">
  <div class="card-body">
    <h2 class="card-title">Selling</h2>
    
    <p class="card-text">

<div id="marketplace_selling">
</div>

    </p>
    
  </div>
</div>


{%endblock%}

{% block js_footer %}


function reload_sell()
{
 $.ajax({
            type: "GET",
            url: {% url 'xchange:marketplace_selling' %},  // URL to your view that serves new info
            data: {}
        })
        .done(function(response) {
            $('#marketplace_selling').html(response);
        });

}

function reload_buy()
{
	 $.ajax({
            type: "GET",
            url: {% url 'xchange:marketplace_buying' %},  // URL to your view that serves new info
            data: {}
        })
        .done(function(response) {
            $('#marketplace_buying').html(response);
        });
}

function reload_all()
    {
    	reload_sell();
    	reload_buy();
    }

    $(document).ready(function()
    {
    	console.log('Ready');

    	reload_all();

    })




{% endblock %}

xchange/templates/marketplace_buy.html
{% load webapp_extras %}

{% if buy_trades %}
<table class="table">
  <tbody>

{% for t in buy_trades %}
<tr>
<td>{{t.buyer}}</td>
<td>wants to buy</td>
<td>{{t.runner}}</td>
      <td>for {{t.print_price}}</td>
      <td> 
      {% if t.buyer == user.investor %}
      <button id="C{{t.id}}" value="C" name="C" onclick="respond_to_open_trade({{t.id}}, '{{t.CANCELLED}}', {{user.investor.id}})">Cancel</button>
      {% else %}
      {% check_investor_can_fulfil_trade t as make_trade_flag %}

{% if make_trade_flag %} 
      
          <button id="A{{t.id}}" value="A" name="A" onclick="respond_to_open_trade({{t.id}}, '{{t.ACCEPTED}}', {{user.investor.id}})">Make trade</button>
        {% else %} {% endif %}
      {% endif %}
      
      </td>
</tr>
{% endfor %}

</tbody>
</table>

{% else %}
Nothing to show
{% endif %}

xchange/templates/marketplace_sell.html
{% if sell_trades %}
<table class="table">
  <tbody>


{% for t in sell_trades %}
<tr>
<td>{{t.seller}}</td>
<td>wants to sell</td>
<td>{{t.share.runner}}</td>
      <td>for {{t.print_price}}</td>
      <td> Actions <!-- <button id="C{{t.id}}" value="C" name="C" onclick="respond_to_trade({{t.id}}, '{{t.CANCELLED}}')">Cancel</button>-->
        
      </td>
</tr>
{% endfor %}


</tbody>
</table>

{% else %}
Nothing to show
{% endif %}

xchange/templates/trades.html
{% extends 'xchange_base.html' %}
{% load static %}

{% block title %}Trades{% endblock %}
{% block page_title %}Trades{% endblock %}


{% block content %}

<div class="card" style="width: 48%; float:left;">
  <div class="card-body">
    <h2 class="card-title">Make a trade</h2>
    <!--<h6 class="card-subtitle mb-2 text-muted">Card subtitle</h6>-->
    <p class="card-text">
    	<div id="make_trade">
    	</div>


</p>
    <!--<a href="#" class="card-link">Card link</a>
    <a href="#" class="card-link">Another link</a>-->
  </div>
</div>

<div id="right-container" style="width:48%; float:right;">

<div class="card" style="width: 100%;">
  <div class="card-body">
    <h2 class="card-title">Active trade requests</h2>
    
    <p class="card-text">

<div id="incoming_trades">
</div>

    </p>
    
  </div>
</div>



</div>



<div class="card" style="width: 100%; float:left; margin-top:25px">
  <div class="card-body">
    <h2 class="card-title">Trading history</h2>
    <!--<h6 class="card-subtitle mb-2 text-muted">Card subtitle</h6>-->
    <p class="card-text">

    	<div id="past_trades">
    	</div>

    </p>
    <!--<a href="#" class="card-link">Card link</a>
    <a href="#" class="card-link">Another link</a>-->
  </div>
</div>


          {%endblock%}


      {% block footer %}


  <script>


  

    function reload_incoming_trades() 
    {
    	/* Some data to send to the back end */
    	var append_increment = 0;

        $.ajax({
            type: "GET",
            url: {% url 'xchange:incoming_trades' %},  // URL to your view that serves new info
            data: {'append_increment': append_increment}
        })
        .done(function(response) {
            $('#incoming_trades').html(response);
            append_increment += 10;
        });
    }

    function reload_past_trades() 
    {
        $.ajax({
            type: "GET",
            url: {% url 'xchange:past_trades' %},  // URL to your view that serves new info
            data: {}
        })
        .done(function(response) {
            $('#past_trades').html(response);
        });
    }

    function reload_make_trades() 
    {
        $.ajax({
            type: "GET",
            url: {% url 'xchange:make_trade' %},  // URL to your view that serves new info
            data: {}
        })
        .done(function(response) {
            $('#make_trade').html(response);
        });
    }

    function makeTradeSell()
    {
    	var runner_id = $('#trade_share option:selected').val();
    	var num_shares = $('#num_shares').val();
    	var share_price = $('#share_price').val(); 
    	var buyer_id = $('#buyer_id').val();
    	var seller_id = {{request.user.investor.id}};

    	makeTrade(seller_id, buyer_id, runner_id, num_shares, share_price);
    }

        function makeTradeBuy()
    {
    	var buyer_id = {{request.user.investor.id}};
    	var num_shares = $('#num_shares_buy').val();
    	var share_price = $('#share_price_buy').val(); 
    	var seller_id = $('#seller_id_responsive option:selected').val();
    	var runner_id = $('#trade_share_buy option:selected').val();

		makeTrade(seller_id, buyer_id, runner_id, num_shares, share_price);


    }

    function makeTrade(seller_id, buyer_id, runner_id, num_shares, share_price)
    {


    	
    	console.log("Create trade from: " + seller_id.toString() + " to: " + buyer_id.toString() + " for " + num_shares.toString() + " in " + runner_id.toString() + " @ " + share_price.toString() + " each");
    	$.ajax({
            type: "GET",
            url: {% url 'xchange:create_trade' %},  // URL to your view that serves new info
            data: {'seller_id': seller_id, 'runner_id': runner_id, 'num_shares': num_shares, 'share_price': share_price, 'buyer_id': buyer_id}
        }).done(function(response)
        {
        	/* Check if response is success.
        	Possible issues:

        	1) Seller does not have this many shares to sell
        	2) You're trying to spend more money than you have


        	 */
        	console.log(response);
        	
        	if (response.status != 0)
        	{
        		alert(response.err_msg);
        	}
        	else
        	{
	        	if (response.status == 1)
	        	{
	        		if (seller_id == {{user.investor.id}})
	        		{
	        			alert('You do not have this many shares to sell');	
	        		}
	        		else
	        		{
	        			alert('The seller does not have this many shares to sell');
	        		}
	       		 }
	        	else if (response.status == 2)
	        	{
					alert('You don\'t have enough capital to buy these shares');
	        	}
	        	else if (response.status != 0)
	        	{
	        		alert('Unknown error, sorry');
	        	}
        }

        	reload_all();
        });
    }





    function respond_to_trade(trade_id, response)
    {
    	console.log("Trade ID: " + trade_id.toString() + ", response: " + response.toString());
    	$.ajax({
            type: "GET",
            url: {% url 'xchange:respond_to_trade' %},  // URL to your view that serves new info
            data: {'trade_id': trade_id, 'response': response}
        }).done(function(response) {

console.log(response);
        	if (!response.trade_allowed)
        	{
				alert('Unable to process request');
        	}
        	reload_all();

        });
    }

        



    function reload_all()
    {
    	reload_past_trades();
    	reload_incoming_trades();
    	reload_make_trades();
    	//reload_outgoing_trades();
    }

    $(document).ready(function()
    {
    	console.log('Ready');

    	reload_all();



    	$(document.body).on('change','#trade_share_buy',function()
    		{
    				var runner_id = $('#trade_share_buy').find(":selected").val(); //$('#trade_share_buy option:selected').val();

    				console.log(runner_id);

    				console.log('Runner selected: ' + runner_id.toString());
    				update_investors_with_shares(runner_id);
    		});

    });

    function update_investors_with_shares(runner_id){
    				

        $.ajax({
        	type: "GET",
            url: {% url 'xchange:get_investors_for_runner' %},  // URL to your view that serves new info
            data: {'runner_id': runner_id}
        })
        .done(function(response) {

            //$('#make_trade').html(response);

            newOptions = response.investors;

            console.log(response);
            console.log(newOptions);

            $('#seller_id_responsive option:gt(0)').remove(); // remove all options, but not the first 
            var $el = $("#seller_id_responsive");

$.each(newOptions, function(key,value) {

	var investor_id = value['investor_id'];

	// Skip currently logged in user
	var current_investor_id = {{request.user.investor.id}};
	if (investor_id != current_investor_id)
	{
	var txt = value['investor_name'] + " - " + value['num_shares'] + " share(s)";

  $el.append($("<option></option>").attr("value", investor_id).text(txt));
}
});

           // console.log(response);

        });

    }

   


  </script>

    
    {% endblock %}