accounts/urls.py
# accounts/urls.py
from django.urls import path

from . import views

app_name = 'accounts'
urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup'),
]

betting/urls.py
from django.urls import path, include

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('market/<int:id>/', views.market),
    path('placeBet/<int:market_id>/', views.place_bet),
    ]

ouccc/urls.py
from django.contrib import admin
from django.urls import include, path
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('betting/', include('betting.urls')),
    path('xchange/', include('xchange.urls')),
    path('', views.home, name='Home'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')) # new
]

handler404 = 'ouccc.views.handler404'
handler500 = 'ouccc.views.handler500'
# handler403 = views.handler403

betting/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
import datetime
from django.utils import timezone


class Club(models.Model):
    club_name = models.CharField(max_length=100)

    def __repr__(self):
        return self.club_name

    def __str__(self):
        return self.__repr__()

class Competitor(models.Model):
    name = models.CharField(max_length=100)
    club = models.ForeignKey(Club, on_delete=models.CASCADE)

    def __repr__(self):
        return '%s (%s)' % (self.name, self.club)

    def __str__(self):
        return self.__repr__()

class Event(models.Model):
    date = models.DateField()
    name = models.CharField(max_length=200)
    location = models.CharField(max_length=200)

    def __str__(self):
        return self.name

# E.g. Varsity XC Men's race 2019
class Competition(models.Model):
    name = models.CharField(max_length=100)
    start_date = models.DateTimeField()
    end_date = models.DateTimeField()
    event = models.ForeignKey(Event, on_delete=models.CASCADE)
    # location = models.CharField(max_length=200)

    competitors = models.ManyToManyField(Competitor)

    def __repr__(self):
        return '%s %s' % (self.name, self.start_date)

    def __str__(self):
        return self.__repr__()

    @property
    def can_place_bet(self):
        return timezone.now() < self.start_date



class Team(models.Model):
    club = models.ForeignKey(Club, on_delete=models.CASCADE)
    team_name = models.CharField(max_length=100)

    def __repr__(self):
        return '%s - %s' % (self.club, self.team_name)

    def __str__(self):
        return self.__repr__()


# E.g. Women's winner
# Can be many markets per event
class Market(models.Model):

    name = models.CharField(max_length=100)
    event = models.ForeignKey(Competition, on_delete=models.CASCADE)
    # type = models.CharField(max_length=2, choices=TYPE_CHOICES, default=PLACING)

    # Options may be a fixed list, or freeform
    # runners = models.ManyToManyField(Runner)

    def __str__(self):
        return '%s - %s' % (self.event.name, self.name)

    def get_existing_bets(self):
        '''

        :return: dict mapping competitor names to their total value
        '''


        comps_value = {}

        # Assumes bet placings"

        all_bets = BetPlacing.objects.filter(market=self)
        print(all_bets)

        for bet in all_bets:

            if bet.competitor.name in comps_value:
                comps_value[bet.competitor.name] += bet.price
            else:
                comps_value[bet.competitor.name] = bet.price

        print(comps_value)
        return comps_value


# Predict who finishes in a particular place
class MarketPlacing(Market):
    # runners = models.ManyToManyField(Competitor)
    placing = models.IntegerField()

    def __str__(self):
        return '%s - %s, Position: %s' % (self.event.name, self.name, self.placing)

# class MarketPlacing(Market):
#     # runners = models.ManyToManyField(Competitor)
#     placing = models.IntegerField()
#
#     def __str__(self):
#         return '%s - %s, Position: %s' % (self.event.name, self.name, self.placing)
#

class Punter(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()
    user = models.OneToOneField( get_user_model(),on_delete=models.CASCADE)

    @property
    def get_profit(self):
        #TODO
        return 0.0
    @property
    def get_ranking(self):
        profit = self.get_profit()



        if profit < 0:
            return 'Chopper'
        elif profit >=0:
            return 'Cowley Club'


    def __str__(self):
        return self.name

# Make sure we make new punters for new users
@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Punter.objects.create(user=instance, name=instance.get_username())

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.punter.save()


# Links a punter, option, and market
# Can be many bets per any other object
class Bet(models.Model):
    market = models.ForeignKey(Market, on_delete=models.CASCADE)
    # option = models.ForeignKey(Option, on_delete=models.CASCADE)
    punter = models.ForeignKey(Punter, on_delete=models.CASCADE)
    price = models.FloatField()

    def __str__(self):
        return '%s / %s / £%s' % (self.market, self.punter, self.price)


class BetPlacing(Bet):
    competitor = models.ForeignKey(Competitor, on_delete=models.CASCADE)

class Result(models.Model):
    runner = models.ForeignKey(Competitor, on_delete=models.CASCADE)
    event = models.ForeignKey(Competition, on_delete=models.CASCADE)
    time = models.DurationField()
    position = models.IntegerField()

    def __str__(self):
        return '%s - %d) %s,  %s' % (self.event.name, self.runner.name, self.time, self.position)

betting/forms.py
import csv
from django import forms
from .models import Competitor
import datetime

class CompetitorInput(forms.Form):
    file = forms.FileField()
    # place = forms.ModelChoiceField(queryset=Place.objects.all())

    def save(self):
        records = csv.reader(self.cleaned_data["file"])
        for line in records:
            input_data = Competitor()
            input_data.name = line[0]
            input_data.club = line[1]
            # input_data.time = datetime.strptime(line[1], "%m/%d/%y %H:%M:%S")
            # input_data.data_1 = line[2]
            # input_data.data_2 = line[3]
            # input_data.data_3 = line[4]
            input_data.save()


class CsvImportForm(forms.Form):
    csv_file = forms.FileField()

betting/views.py
from django.shortcuts import render, render_to_response
from .models import Competition, Market, Punter, Bet, BetPlacing, Competitor, Event
from django.http import JsonResponse
# Create your views here.
from .forms import CompetitorInput
from django.contrib.admin.views.decorators import staff_member_required



from django.http import HttpResponse


def index(request):

    context = {'title': 'Bets',
               'comps': Competition.objects.all(),
               'events': Event.objects.all()}

    return render(request, 'bettingHome.html', context)



def market(request, id):

    market = Market.objects.get(id=id)
    competition = Competition.objects.get(market=market)

    # Check if user has placed bet in market
    bet = None
    if request.user.is_authenticated:
        punter = Punter.objects.get(user=request.user)

        try:
            # TODO: add other bet types here
            bet = BetPlacing.objects.get(punter=punter,market=market)


        except Bet.DoesNotExist:
            bet = None

    # dict of copmetitors->price
    bets = market.get_existing_bets()

    existingBets = {}
    existingBets['labels'] = ['%s (£%.2f)' % (runner, bets[runner]) for runner in list(bets.keys())] #list(bets.keys())

    existingBets['price']= [bets[k] for k in list(bets.keys())]

    print(existingBets)

    # For some reason have to had 'user' here explicitly
    return render_to_response('market.html', { 'market': market,
                                               'competition': competition,
                                               'bet': bet,
                                               'user': request.user,
                                               'existingBets': existingBets})


def place_bet(request, market_id):

    # posts = Post.objects.all()
    response_data = {}

    if request.POST.get('action') == 'post':
        competitor_id = request.POST.get('competitor')
        price = request.POST.get('price')


        comp = Competitor.objects.get(id=competitor_id)

        market = Market.objects.get(id=market_id)
        print('Competitor: ' + str(comp) + ', price: ' + str(price) + ', current user: ' + str(request.user))

        competition = market.event
        if not competition.can_place_bet:
            print('Competition has started, cannot place bet')
            response_data['error'] = 'Too late to place bet.'

        else:
            current_punter = Punter.objects.get(user=request.user)
            bet = BetPlacing.objects.create(competitor = comp, price=price, market=market, punter=current_punter)

            print('Placed bet: ' + str(bet))

        return JsonResponse(response_data)

    else:
        return HttpResponse('Go away')

betting/templates/bettingHome.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}{{ title }}{% endblock %}

{% block head %}
{% load tz %} <!--Time zones -->

<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.5.0/Chart.min.js"></script>


<script>

$("ul.nav-tabs a").click(function (e) {
  e.preventDefault();
    $(this).tab('show');
});


   function showMarket(div_id, market_id, do_toggle){


//make an ajax call and get status value using the same 'id'
//var var1= document.getElementById("div_id").value;
$.ajax({

        type:"GET",//or POST
        url:'market/' + market_id + '/',
        success:function(data){
               // process on data
               var elName = '#' + div_id;
               $(elName).html(data);

               if (do_toggle) {
               $(elName).toggle();
               }

        }
     })

}


function placeBet(market_id, comp_id) {

document.getElementById('marketErr'+market_id).innerHTML = '';

/* Perform some basic validation */
var price = document.getElementById('price' + market_id).value;

var selected = document.querySelector('input[name=competitorSelect' + market_id +']:checked');


if (price < 0 || price > 10) {
    /*alert('Invalid');*/
} else if (selected == null) {

document.getElementById('marketErr'+market_id).innerHTML = 'Error: no competitor selected';

} else {


$.ajax({

        type:'POST',
        url:'placeBet/' + market_id + '/',
        data:{
            competitor:$('input[name=competitorSelect' + market_id +']:checked').val(),
            price:$('#price' + market_id).val(),
            csrfmiddlewaretoken:$('input[name=csrfmiddlewaretoken]').val(),
            action: 'post'
        },
        success:function(json){
        showMarket('marketDetails' + comp_id, market_id, false);
        }
     })

}

}



</script>
{% endblock %}

{% block app_name %}
<a class="nav-link" href="/betting">Betting pool</a>
{% endblock %}

{% block content %}
<!--<div class="container">
    <div style="float:right; width:60%">
        <div style="float:right; width:200px">
            {% if user.is_authenticated %}
            Logged in as {{ user.username }}<br>

            (<a href="{% url 'logout' %}?next={{ request.path | urlencode }}">logout</a>, <a href="{% url 'password_reset' %}?next={% url 'login' %}">reset password</a>). <br>
            Currently wagered: ... <br>
            Profit/loss: ... <br>
            Ranking: Chopper <br>
            {% else %}

            <a href="{% url 'login' %}?next={{ request.path | urlencode }}">Login</a> or <a href="{% url 'accounts:signup' %}?afterlogin={{ request.path | urlencode }}">signup</a> to place bets.
            {% endif %}

        </div>
    </div>
</div>-->


<div class="container">




    <form method="POST" id="marketsForm">
        {% csrf_token %}

        <div class="tabbable boxed parentTabs">
            <ul class="nav nav-tabs">
                <li class="navTitle"><span class="badge badge-primary">Event</span></li>
                {% for event in events %}
                <li><a href="#event{{event.id}}">{{event.name}}</a></li>
                {% endfor %}
            </ul>
            <div class="tab-content">


                {% for event in events %}
                <div class="tab-pane fade" id="event{{event.id}}">
                    <div class="tabbable">
                        <ul class="nav nav-tabs">
                            <li class="navTitle"><span class="badge badge-primary">Race</span></li>
                            {% if event.competition_set.all %}
                            {% for comp in event.competition_set.all %}
                            <li><a href="#comp{{comp.id}}">{% if not comp.can_place_bet %}<span class="glyphicon glyphicon-lock" aria-hidden="true"></span> {% endif %}{{comp.name}}</a> </li>
                            {% endfor %}
                            {% else %}
                            <li>No races available</li>
                            {% endif %}
                        </ul>
                        <div class="tab-content">

                            {% for comp in event.competition_set.all %}
                            <div class="tab-pane fade" id="comp{{comp.id}}">

                                <ul class="nav nav-tabs">
                                     <li class="navTitle"><span class="badge badge-primary">Market</span></li>
                                     {% for m in comp.market_set.all %}
                                    <li><a href='#' onclick="showMarket('marketDetails{{comp.id}}', {{m.id}}, false)">{{m.name}}</a></li>
                                    {% endfor %}
                                </ul>

                                <div id="marketDetails{{comp.id}}"></div>


                            </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>

    </form>
</div>


<script>
    $("#marketsForm").submit(function(event) {

                /* stop form from submitting normally */
                event.preventDefault();
                });

                $("ul.nav-tabs a").click(function (e) {
  e.preventDefault();
    $(this).tab('show');
});


</script>



{% endblock %}

betting/templates/market.html
<div class="navTitle" style="float:left">
    {% if bet %}
    <span class="badge badge-secondary">Bet placed</span>
    {% elif not competition.can_place_bet %}
    <span class="badge badge-secondary">Betting closed</span>
    {% else %}
    <span class="badge badge-secondary">Place bet</span>
    {% endif %}
</div>

<div class="form-group mx-sm-3 mb-2 competitor-select" style="float:right; width:80%; margin-top:5px;" >


    {% for competitor in competition.competitors.all %}

    <input type="radio" id="{{market.id}}_{{competitor.id}}" name="competitorSelect{{market.id}}" value="{{competitor.id}}"
           {% if bet %}
           {% if bet.competitor.id == competitor.id %}
           class="preselected" checked
           {% else %}
           class="unselectable"  disabled readonly
           {% endif %}
           {% endif %}
           {% if not user.is_authenticated or  not competition.can_place_bet %} disabled readonly {% endif %}
           >

    <label for="{{market.id}}_{{competitor.id}}" {% if bet or not competition.can_place_bet %}class="noselect"{% endif %}>{{competitor}}</label>

    {% endfor %}
    <div id="marketErr{{market.id}}"></div>


    {% if user.is_authenticated   %}


    <div class="row">
        <div class="col-sm-4">
            <div class="input-group">
                {% if  bet or competition.can_place_bet %}

                <div class="input-group-prepend">
                    <span class="input-group-text">£</span>
                </div>
                <input class="form-control" type="number" min="0" max="10" step="0.01" id="price{{market.id}}"
                       {% if not bet == None %}placeholder="{{bet.price}}" readonly{% else %}placeholder="0.0"{% endif %}
                       {% if not competition.can_place_bet or not user.is_authenticated %}readonly{% endif %}
                >
                <div class="input-group-append">
                    <button type="submit" class="btn {% if bet %} btn-secondary {% else %} btn-primary {% endif %}" onclick="placeBet({{market.id}}, {{competition.id}})" {% if not bet == None %} disabled {% endif %}>Place bet</button>
                </div>
                {% endif %}
            </div>
        </div>
    </div>





    {% endif %}

</div>


<div class="input-group mb-1 mr-sm-1">
</div>

{% if  not user.is_authenticated   %}

<div class="alert alert-warning" role="alert">
    <a href="{% url 'login' %}?next={{ request.path | urlencode }}">Login</a> or <a href="{% url 'accounts:signup' %}?next={{ request.path | urlencode }}">signup</a> to place a bet.
</div>

{% endif %}


<div class="card" style="width: 38rem;">
  <div class="card-header">
    Current bets
  </div>

    <div class="container">
        <div class="chart-container" style="position: relative; height:12rem; width:36rem;">
            <canvas id="pieChart{{market.id}}" width="3" height="1"></canvas>
        </div>
    </div>
</div>


<script>
var ctx = document.getElementById('pieChart{{market.id}}').getContext('2d');
var myChart = new Chart(ctx, {
    type: 'pie',
    data: {
        datasets: [{
            data: [{% for v in existingBets.price %} {{v}} {% if not forloop.last %},{% endif %} {% endfor %}],
            backgroundColor: ["#F7464A", "#46BFBD", "#FDB45C", "#949FB1", "#4D5360"],
            labels: [{% for l in existingBets.labels %} "{{l}}" {% if not forloop.last %},{% endif %} {% endfor %}]
    }],

    // These labels appear in the legend and in the tooltips when hovering different arcs
    labels: [{% for l in existingBets.labels %} "{{l}}" {% if not forloop.last %},{% endif %} {% endfor %}]
    },
    options: {
    legend: {position: 'right'},
    tooltips: {
            callbacks: {
            // Just use the label (which includes the money value)
                label: function(tooltipItem, data) {
                    return data.labels[tooltipItem['index']];
                     }
            }
        }
    }
});
</script>